base: &base
  machine:
    image: ubuntu-1604:202007-01

version: 2.1
orbs:
  docker: circleci/docker@1.3.0

commands:
  setupenv:
    description: "Quick Environment setup"
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export TAG=latest' >> $BASH_ENV
            echo 'export IMAGE_NAME=cicd_demo' >> $BASH_ENV

  setupenvdev:
    description: "Quick Setup For Development Setup"
    steps:
      - checkout
      - run:
          name: Setup Development Environment Variables
          command: |
            echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
            echo 'export IMAGE_NAME=cicd_demo_dev' >> $BASH_ENV
  cache-app:
    description: "Cache the Production Docker Image"
    parameters:
      cache:
        type: boolean
        default: false
    steps:
      - when:
          condition: <<parameters.cache>>
          steps:
            - run:
                name: Save Docker Image
                command: |
                  mkdir -p docker-cache
                  docker save -o docker-cache/built-image.tar aaronzinhoo/$IMAGE_NAME:$TAG
            - save_cache:
                key: docker_cache_key-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                  - docker-cache

# Jobs Definitions
jobs:
  build:
    <<: *base
    steps:
      - setupenv
      - run:
          name: Build production docker image
          command: |
            npm run build:prod
  build-and-cache:
    <<: *base
    steps:
      - setupenv
      - run:
          name: Build Production Docker Image
          command: |
             npm run build:prod
      - cache-app:
          cache: true
  build-and-cache-dev:
    <<: *base
    steps:
      - setupenvdev
      - run:
          name: Build Production Docker Image
          command: |
             npm run build:dev
      - cache-app:
          cache: true
  publish:
    <<: *base
    steps:
      - setupenv
      - restore_cache:
          key: docker_cache_key-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Load Image from Docker Cache
          command: |
            docker load < docker-cache/built-image.tar
      - run:
          name: Publish Docker Image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push aaronzinhoo/$IMAGE_NAME:$TAG
  publish-dev:
    <<: *base
    steps:
      - setupenvdev
      - restore_cache:
          key: docker_cache_key-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Load Image from Docker Cache
          command: |
            docker load < docker-cache/built-image.tar
      - run:
          name: Publish Docker Image
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push aaronzinhoo/$IMAGE_NAME:$TAG
workflows:
  build-deploy-dev:
    jobs:
      - build-and-cache-dev:
          filters:
            branches:
              only:
                - develop
      - publish-dev:
          requires:
            - build-and-cache-dev
          filters:
            branches:
              only:
                - develop
  build-deploy:
    jobs:
      - build-and-cache:
          filters:
            branches:
              only:
                - master
      -  publish:
          requires:
            - build-and-cache
          filters:
            branches:
              only:
                - master
      # - docker/publish:
      #     image: aaronzinhoo/$CIRCLE_PROJECT_REPONAME
      #     tag: latest
      #     dockerfile: Dockerfile
      #     deploy: true
      #     filters:
      #       branches:
      #         only:
      #           - master
