version: 2.1

orbs:
  docker: circleci/docker@1.3.0

workflows:
  build-deploy:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          dockerfile: Dockerfile
          deploy: true
          filters:
            branches:
              only:
                - master
